### ISSUE TITLE
doesn't compile with Aeson 2.0.3.0

### ISSUE THREAD

**Issue by mwotton** [lehins/wai-middleware-auth#31]
```
wai-middleware-auth              > /tmp/stack-8aad968b153b4009/wai-middleware-auth-0.2.6.0/src/Network/Wai/Auth/Config.hs:29:15: error:
wai-middleware-auth              >     Ambiguous occurrence ‘Key’
wai-middleware-auth              >     It could refer to
wai-middleware-auth              >        either ‘Data.Aeson.Key’,
wai-middleware-auth              >               imported from ‘Data.Aeson’ at src/Network/Wai/Auth/Config.hs:14:1-27
wai-middleware-auth              >               (and originally defined in ‘Data.Aeson.Key’)
wai-middleware-auth              >            or ‘Web.ClientSession.Key’,
wai-middleware-auth              >               imported from ‘Web.ClientSession’ at src/Network/Wai/Auth/Config.hs:20:42-44
wai-middleware-auth              >    |
wai-middleware-auth              > 29 |   | SecretKey Key -- ^ Serialized and base64 encoded form of a secret key. Use
wai-middleware-auth              >    |               ^^^
```

**Comment by andreabedini** [comment]
Hi @lehins, is there any chance you can add a revision introducing an upper bound on the dependency on aeson? I think we need `aeson <2`.

**Comment by lehins** [comment]
Sorry @andreabedini, but I no longer maintain the package. You need to reach out to someone at @fpco for that, maybe @snoyberg can help you with this.

**Comment by andreabedini** [comment]
Thanks @lehins!

**Comment by andreabedini** [comment]
btw, a cabal file revision is something the Hackage Trustees can do in principle, if welcomed by the maintainers.
