### ISSUE TITLE
Doesn't compile with newest version of `hoauth2>=1.11`

### ISSUE THREAD

**Issue by lehins** [lehins/wai-middleware-auth#17]
`OAuth2.oauthClientSecret` in `hoauth2` is now `Maybe Text` vs just `Text` in prior versions

```
/home/lehins/fpco/wai-middleware-auth/src/Network/Wai/Middleware/Auth/OAuth2.hs:102:33: error:
    • Couldn't match expected type ‘Maybe T.Text’
                  with actual type ‘T.Text’
    • In the ‘oauthClientSecret’ field of a record
      In the expression:             
        OA2.OAuth2                   
          {oauthClientId = getClientId oa2ClientId,
           oauthClientSecret = getClientSecret oa2ClientSecret,
           oauthOAuthorizeEndpoint = authEndpointURI,
           oauthAccessTokenEndpoint = accessTokenEndpointURI,
           oauthCallback = Just callbackURI}
      In an equation for ‘oauth2’:   
          oauth2                     
            = OA2.OAuth2             
                {oauthClientId = getClientId oa2ClientId,
                 oauthClientSecret = getClientSecret oa2ClientSecret,
                 oauthOAuthorizeEndpoint = authEndpointURI,
                 oauthAccessTokenEndpoint = accessTokenEndpointURI,
                 oauthCallback = Just callbackURI}
    |                                
102 |           , oauthClientSecret = getClientSecret oa2ClientSecret
    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
